//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolPlanilla.Interface.ProxyWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyWeb.IServicioPlanilla")]
    public interface IServicioPlanilla {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/TestConexion", ReplyAction="http://tempuri.org/IServicioPlanilla/TestConexionResponse")]
        bool TestConexion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/TestConexion", ReplyAction="http://tempuri.org/IServicioPlanilla/TestConexionResponse")]
        System.Threading.Tasks.Task<bool> TestConexionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObreroResponse")]
        SolPlanilla.BE.BeMaestroCategoriaObrero ConsultarCategoriaObrero(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObreroResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroCategoriaObrero> ConsultarCategoriaObreroAsync(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObreroLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObreroListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BeMaestroCategoriaObrero> ConsultarCategoriaObreroLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObreroLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarCategoriaObreroListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroCategoriaObrero>> ConsultarCategoriaObreroListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarCategoriaObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarCategoriaObreroResponse")]
        SolPlanilla.BE.BeMaestroCategoriaObrero GrabarCategoriaObrero(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarCategoriaObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarCategoriaObreroResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroCategoriaObrero> GrabarCategoriaObreroAsync(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarDocumento", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarDocumentoResponse")]
        SolPlanilla.BE.BeMaestroDocumento ConsultarDocumento(SolPlanilla.BE.BeMaestroDocumento pDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarDocumento", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarDocumentoResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroDocumento> ConsultarDocumentoAsync(SolPlanilla.BE.BeMaestroDocumento pDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarDocumentoLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarDocumentoListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BeMaestroDocumento> ConsultarDocumentoLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarDocumentoLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarDocumentoListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroDocumento>> ConsultarDocumentoListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarDocumento", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarDocumentoResponse")]
        SolPlanilla.BE.BeMaestroDocumento GrabarDocumento(SolPlanilla.BE.BeMaestroDocumento pDocumento, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarDocumento", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarDocumentoResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroDocumento> GrabarDocumentoAsync(SolPlanilla.BE.BeMaestroDocumento pDocumento, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarObreroResponse")]
        SolPlanilla.BE.BeMaestroObrero ConsultarObrero(SolPlanilla.BE.BeMaestroObrero pObrero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarObreroResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObrero> ConsultarObreroAsync(SolPlanilla.BE.BeMaestroObrero pObrero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarObreroLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarObreroListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObrero> ConsultarObreroLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarObreroLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarObreroListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObrero>> ConsultarObreroListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarObreroResponse")]
        SolPlanilla.BE.BeMaestroObrero GrabarObrero(SolPlanilla.BE.BeMaestroObrero pObrero, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarObreroResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObrero> GrabarObreroAsync(SolPlanilla.BE.BeMaestroObrero pObrero, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarEmpresaLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarEmpresaListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BeMaestroEmpresa> ConsultarEmpresaLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarEmpresaLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarEmpresaListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroEmpresa>> ConsultarEmpresaListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarEmpresa", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarEmpresaResponse")]
        SolPlanilla.BE.BeMaestroEmpresa GrabarEmpresa(SolPlanilla.BE.BeMaestroEmpresa pEmpresa, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarEmpresa", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarEmpresaResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroEmpresa> GrabarEmpresaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarUitLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarUitListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BeMaestroUit> ConsultarUitLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarUitLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarUitListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroUit>> ConsultarUitListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarUit", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarUitResponse")]
        SolPlanilla.BE.BeMaestroUit GrabarUit(SolPlanilla.BE.BeMaestroUit pUit, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarUit", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarUitResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroUit> GrabarUitAsync(SolPlanilla.BE.BeMaestroUit pUit, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarTasaLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarTasaListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BeMaestroTasa> ConsultarTasaLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarTasaLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarTasaListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroTasa>> ConsultarTasaListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarTasa", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarTasaResponse")]
        SolPlanilla.BE.BeMaestroTasa GrabarTasa(SolPlanilla.BE.BeMaestroTasa pTasa, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarTasa", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarTasaResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroTasa> GrabarTasaAsync(SolPlanilla.BE.BeMaestroTasa pTasa, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarObrasLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarObrasListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObras> ConsultarObrasLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarObrasLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarObrasListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObras>> ConsultarObrasListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarPeriodoLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarPeriodoListaResponse")]
        System.Collections.Generic.List<SolPlanilla.BE.BePeriodos> ConsultarPeriodoLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ConsultarPeriodoLista", ReplyAction="http://tempuri.org/IServicioPlanilla/ConsultarPeriodoListaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BePeriodos>> ConsultarPeriodoListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarPeriodos", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarPeriodosResponse")]
        SolPlanilla.BE.BePeriodos GrabarPeriodos(SolPlanilla.BE.BePeriodos pPeriodo, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/GrabarPeriodos", ReplyAction="http://tempuri.org/IServicioPlanilla/GrabarPeriodosResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BePeriodos> GrabarPeriodosAsync(SolPlanilla.BE.BePeriodos pPeriodo, bool pGrabar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ImportarObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/ImportarObreroResponse")]
        SolPlanilla.BE.BeMaestroObrero ImportarObrero(SolPlanilla.BE.BeMaestroObrero pObrero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ImportarObrero", ReplyAction="http://tempuri.org/IServicioPlanilla/ImportarObreroResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObrero> ImportarObreroAsync(SolPlanilla.BE.BeMaestroObrero pObrero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ImportarObras", ReplyAction="http://tempuri.org/IServicioPlanilla/ImportarObrasResponse")]
        SolPlanilla.BE.BeMaestroObras ImportarObras(SolPlanilla.BE.BeMaestroObras pObra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPlanilla/ImportarObras", ReplyAction="http://tempuri.org/IServicioPlanilla/ImportarObrasResponse")]
        System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObras> ImportarObrasAsync(SolPlanilla.BE.BeMaestroObras pObra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPlanillaChannel : SolPlanilla.Interface.ProxyWeb.IServicioPlanilla, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPlanillaClient : System.ServiceModel.ClientBase<SolPlanilla.Interface.ProxyWeb.IServicioPlanilla>, SolPlanilla.Interface.ProxyWeb.IServicioPlanilla {
        
        public ServicioPlanillaClient() {
        }
        
        public ServicioPlanillaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPlanillaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPlanillaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPlanillaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TestConexion() {
            return base.Channel.TestConexion();
        }
        
        public System.Threading.Tasks.Task<bool> TestConexionAsync() {
            return base.Channel.TestConexionAsync();
        }
        
        public SolPlanilla.BE.BeMaestroCategoriaObrero ConsultarCategoriaObrero(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero) {
            return base.Channel.ConsultarCategoriaObrero(pCategoriaObrero);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroCategoriaObrero> ConsultarCategoriaObreroAsync(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero) {
            return base.Channel.ConsultarCategoriaObreroAsync(pCategoriaObrero);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BeMaestroCategoriaObrero> ConsultarCategoriaObreroLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarCategoriaObreroLista(pEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroCategoriaObrero>> ConsultarCategoriaObreroListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarCategoriaObreroListaAsync(pEmpresa);
        }
        
        public SolPlanilla.BE.BeMaestroCategoriaObrero GrabarCategoriaObrero(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero, bool pGrabar) {
            return base.Channel.GrabarCategoriaObrero(pCategoriaObrero, pGrabar);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroCategoriaObrero> GrabarCategoriaObreroAsync(SolPlanilla.BE.BeMaestroCategoriaObrero pCategoriaObrero, bool pGrabar) {
            return base.Channel.GrabarCategoriaObreroAsync(pCategoriaObrero, pGrabar);
        }
        
        public SolPlanilla.BE.BeMaestroDocumento ConsultarDocumento(SolPlanilla.BE.BeMaestroDocumento pDocumento) {
            return base.Channel.ConsultarDocumento(pDocumento);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroDocumento> ConsultarDocumentoAsync(SolPlanilla.BE.BeMaestroDocumento pDocumento) {
            return base.Channel.ConsultarDocumentoAsync(pDocumento);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BeMaestroDocumento> ConsultarDocumentoLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarDocumentoLista(pEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroDocumento>> ConsultarDocumentoListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarDocumentoListaAsync(pEmpresa);
        }
        
        public SolPlanilla.BE.BeMaestroDocumento GrabarDocumento(SolPlanilla.BE.BeMaestroDocumento pDocumento, bool pGrabar) {
            return base.Channel.GrabarDocumento(pDocumento, pGrabar);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroDocumento> GrabarDocumentoAsync(SolPlanilla.BE.BeMaestroDocumento pDocumento, bool pGrabar) {
            return base.Channel.GrabarDocumentoAsync(pDocumento, pGrabar);
        }
        
        public SolPlanilla.BE.BeMaestroObrero ConsultarObrero(SolPlanilla.BE.BeMaestroObrero pObrero) {
            return base.Channel.ConsultarObrero(pObrero);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObrero> ConsultarObreroAsync(SolPlanilla.BE.BeMaestroObrero pObrero) {
            return base.Channel.ConsultarObreroAsync(pObrero);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObrero> ConsultarObreroLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarObreroLista(pEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObrero>> ConsultarObreroListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarObreroListaAsync(pEmpresa);
        }
        
        public SolPlanilla.BE.BeMaestroObrero GrabarObrero(SolPlanilla.BE.BeMaestroObrero pObrero, bool pGrabar) {
            return base.Channel.GrabarObrero(pObrero, pGrabar);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObrero> GrabarObreroAsync(SolPlanilla.BE.BeMaestroObrero pObrero, bool pGrabar) {
            return base.Channel.GrabarObreroAsync(pObrero, pGrabar);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BeMaestroEmpresa> ConsultarEmpresaLista() {
            return base.Channel.ConsultarEmpresaLista();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroEmpresa>> ConsultarEmpresaListaAsync() {
            return base.Channel.ConsultarEmpresaListaAsync();
        }
        
        public SolPlanilla.BE.BeMaestroEmpresa GrabarEmpresa(SolPlanilla.BE.BeMaestroEmpresa pEmpresa, bool pGrabar) {
            return base.Channel.GrabarEmpresa(pEmpresa, pGrabar);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroEmpresa> GrabarEmpresaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa, bool pGrabar) {
            return base.Channel.GrabarEmpresaAsync(pEmpresa, pGrabar);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BeMaestroUit> ConsultarUitLista() {
            return base.Channel.ConsultarUitLista();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroUit>> ConsultarUitListaAsync() {
            return base.Channel.ConsultarUitListaAsync();
        }
        
        public SolPlanilla.BE.BeMaestroUit GrabarUit(SolPlanilla.BE.BeMaestroUit pUit, bool pGrabar) {
            return base.Channel.GrabarUit(pUit, pGrabar);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroUit> GrabarUitAsync(SolPlanilla.BE.BeMaestroUit pUit, bool pGrabar) {
            return base.Channel.GrabarUitAsync(pUit, pGrabar);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BeMaestroTasa> ConsultarTasaLista() {
            return base.Channel.ConsultarTasaLista();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroTasa>> ConsultarTasaListaAsync() {
            return base.Channel.ConsultarTasaListaAsync();
        }
        
        public SolPlanilla.BE.BeMaestroTasa GrabarTasa(SolPlanilla.BE.BeMaestroTasa pTasa, bool pGrabar) {
            return base.Channel.GrabarTasa(pTasa, pGrabar);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroTasa> GrabarTasaAsync(SolPlanilla.BE.BeMaestroTasa pTasa, bool pGrabar) {
            return base.Channel.GrabarTasaAsync(pTasa, pGrabar);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObras> ConsultarObrasLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarObrasLista(pEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BeMaestroObras>> ConsultarObrasListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarObrasListaAsync(pEmpresa);
        }
        
        public System.Collections.Generic.List<SolPlanilla.BE.BePeriodos> ConsultarPeriodoLista(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarPeriodoLista(pEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SolPlanilla.BE.BePeriodos>> ConsultarPeriodoListaAsync(SolPlanilla.BE.BeMaestroEmpresa pEmpresa) {
            return base.Channel.ConsultarPeriodoListaAsync(pEmpresa);
        }
        
        public SolPlanilla.BE.BePeriodos GrabarPeriodos(SolPlanilla.BE.BePeriodos pPeriodo, bool pGrabar) {
            return base.Channel.GrabarPeriodos(pPeriodo, pGrabar);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BePeriodos> GrabarPeriodosAsync(SolPlanilla.BE.BePeriodos pPeriodo, bool pGrabar) {
            return base.Channel.GrabarPeriodosAsync(pPeriodo, pGrabar);
        }
        
        public SolPlanilla.BE.BeMaestroObrero ImportarObrero(SolPlanilla.BE.BeMaestroObrero pObrero) {
            return base.Channel.ImportarObrero(pObrero);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObrero> ImportarObreroAsync(SolPlanilla.BE.BeMaestroObrero pObrero) {
            return base.Channel.ImportarObreroAsync(pObrero);
        }
        
        public SolPlanilla.BE.BeMaestroObras ImportarObras(SolPlanilla.BE.BeMaestroObras pObra) {
            return base.Channel.ImportarObras(pObra);
        }
        
        public System.Threading.Tasks.Task<SolPlanilla.BE.BeMaestroObras> ImportarObrasAsync(SolPlanilla.BE.BeMaestroObras pObra) {
            return base.Channel.ImportarObrasAsync(pObra);
        }
    }
}
